export const CREATE_MOVIE = "CREATE_MOVIE";
export const RETRIEVE_MOVIES = "RETRIEVE_MOVIES";
export const UPDATE_MOVIE = "UPDATE_MOVIE";
export const DELETE_MOVIE = "DELETE_MOVIE";
export const DELETE_ALL_MOVIES = "DELETE_ALL_MOVIES";

